name: AutoUpdateIndex

on:
  push:
    branches:
      - novels
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fresh:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Setup SSH
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 700 ~/.ssh
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Clone novels library
      run: |
        git clone -b novels https://github.com/${{ github.repository }}.git temp
    - name: Refresh README.md
      run: |
        python main.py
    - name: Commit
      run: |
        git remote set-url origin git@github.com:LightNovels/Home.git
        git config --global user.email lightnovels@lightnovels.org
        git config --global user.name lightnovels
        git add .
        git commit -m "Refreshed" -a
        git push -u origin master
    # - name: GitHub Push
    #   uses: ad-m/github-push-action@v0.6.0
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: ${{ github.ref }}
